main:
  - identifier: blog
    name: Navigate
    weight: 4
    params:
      icon:
        vendor: font-awesome-regular
        name: compass

  - name: Support
    identifier: support
    weight: 100
    #url: https://github.com/hbstack
    params:
      header: The HB support community.
      icon:
        vendor: font-awesome-solid
        name: headset

  - name: Documentation
    parent: support
    url: https://hbstack.dev/
    weight: 1
    params:
      icon:
        vendor: bs
        name: book
        className: text-primary
      description: The documentation.

  - name: GitHub
    parent: support
    url: https://github.com/rootandbeer
    weight: 11
    params:
      icon:
        vendor: fab
        name: github
      description: The code repository.

  - name: Discussion
    parent: support
    url: https://github.com/rootandbeer/rootandbeer.github.io/discussions
    weight: 12
    params:
      icon:
        vendor: font-awesome-regular
        name: comments
        color: green
      description: Ask questions and share your ideas.

  - name: Bug Report
    parent: support
    url: https://github.com/rootandbeer/rootandbeer.github.io/discussions/new?category=issues-and-bugs
    weight: 13
    params:
      icon:
        vendor: font-awesome-solid
        name: bug
        color: red
      description: Tell us about a bug or issue.

  - name: Requests
    parent: support
    url: https://github.com/rootandbeer/rootandbeer.github.io/discussions/new?category=ideas
    weight: 14
    params:
      icon:
        vendor: font-awesome-regular
        name: lightbulb
        color: orange
      description: Suggest new requests for labs or other content.
  
#  - name: Mastodon
#    parent: support
#    url: https://techhub.social/@hbstack
#    weight: 16
#    params:
#      icon:
#        vendor: simple
#        name: mastodon
#      description: Follow us on Mastodon to get latest updates.
