main:
  - identifier: blog
    name: More
    weight: 4
    params:
      icon:
        vendor: mdi
        name: dots-grid
  - name: Support
    identifier: support
    weight: 100
    #url: https://github.com/hbstack
    params:
      header: The root&beer support community.
      icon:
        vendor: font-awesome-solid
        name: headset

#  - name: Documentation
#    parent: support
#    url: https://hbstack.dev/
#    weight: 1
#    params:
#      icon:
#        vendor: bs
#        name: book
#        className: text-primary
#      description: The documentation.

  - name: GitHub
    parent: support
    url: https://github.com/rootandbeer
    weight: 11
    params:
      icon:
        vendor: fab
        name: github
      description: The code repository.

  - name: Discussion
    parent: support
    url: https://github.com/rootandbeer/rootandbeer.github.io/discussions
    weight: 12
    params:
      icon:
        vendor: font-awesome-regular
        name: comments
        color: teal
      description: Ask questions and share your ideas.

  - name: Bug Report
    parent: support
    url: https://github.com/rootandbeer/rootandbeer.github.io/discussions/new?category=issues-and-bugs
    weight: 13
    params:
      icon:
        vendor: font-awesome-solid
        name: bug
        color: red
      description: Tell us about a bug or issue.

  - name: Submit Lab
    parent: support
    url: /pages/submit-lab
    weight: 14
    params:
      icon:
        vendor: mdi
        name: beaker-plus-outline
        color: lime
      description: Submit a lab for review.

  - name: Requests
    parent: support
    url: https://github.com/rootandbeer/rootandbeer.github.io/discussions/new?category=ideas
    weight: 15
    params:
      icon:
        vendor: font-awesome-regular
        name: lightbulb
        color: orange
      description: Suggest new requests for labs or other content.
  
#  - name: Mastodon
#    parent: support
#    url: https://techhub.social/@hbstack
#    weight: 16
#    params:
#      icon:
#        vendor: simple
#        name: mastodon
#      description: Follow us on Mastodon to get latest updates.
